#database connection
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/Auth_App
    username: postgres
    password: Harshal@2003

    # Jpa and Hibernate Configuration
  jpa:          #This Property create Table For Entity
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
logging:
  level:
    org.springframework.security: DEBUG

security:
  jwt:
    secret: ${JWT_SECRET:hfeihfierwidsfhigheuhq3foawj;;fioawjtqwjawnvahfuwh47y34y93udknvfhiewhgiewhhtengkjfhviueahrherwhtri3ertherwhgubfkjhiewrhieriuurehu4y895uwrfkn}
    issuer: ${JWT_ISSUER:api.substring.com}
    access-ttl-seconds: ${JWT_ACCESS_TTL_SECOND:3600}
    refresh-ttl-seconds: ${JWT_REFRESH_TTL_SECOND:86400}
    refresh-token-cookie-name: ${JWT_REFRESH_COOKIE_NAME:refreshToken}
    cookie-secure: ${JWT_COOKIE_SECURE:true}
    cookie-http-only: ${JWT_COOKIE_HTTP_ONLY:true}
    cookie-same-site: ${JWT_COOKIE_SAME_SITE:lax}