#database connection
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/Auth_App
    username: postgres
    password: Harshal@2003

    # Jpa and Hibernate Configuration
  jpa:          #This Property create Table For Entity
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
logging:
  level:
    org.springframework.security: DEBUG
